astrologuesser/urls.py
from django.conf.urls import patterns, url
from astrologuesser import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    # ex: /astrologuesser/5/
    url(r'^specifics/(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    # ex: /astrologuesser/5/results/
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    # ex: /astrologuesser/5/vote/
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

my_django15_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'my_django15_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^astrologuesser/', include('astrologuesser.urls', namespace="astrologuesser")),
    url(r'^admin/', include(admin.site.urls)),

)

astrologuesser/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):              # __unicode__ on Python 2
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text

astrologuesser/views.py
from django.http import Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from astrologuesser.models import Choice, Question
from django.template import RequestContext, loader

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('astrologuesser/index.html')
    context = RequestContext(request, {
        'latest_question_list': latest_question_list,
    })
    return HttpResponse(template.render(context))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'astrologuesser/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'astrologuesser/results.html', { 'question': question})

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # redisplay the voting form
        return render(request, 'astrologuesser/detail.htm', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('astrologuesser:results', args=(p.id,)))

astrologuesser/templates/astrologuesser/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'astrologuesser:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
  {% endfor %}
  <input type="submit" value="Vote" />
</form>

astrologuesser/templates/astrologuesser/index.html
<br />
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!-- OLD: <li><a href="{% url 'astrologuesser:detail' question.id %}">{{ question.question_text }}</a></li> -->
        <!-- NEW:  -->
        <h1>{{ question.question_text }}</h1>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="{% url 'astrologuesser:vote' question.id %}" method="post">
          {% csrf_token %}
          {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />

        <!-- /NEW  -->
    {% endfor %}
    {% endfor %}
    <br />
    <br />
    <input type="submit" value="Submit" />
  </form>
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

astrologuesser/templates/astrologuesser/results.html
<h1>{{ question.question_text}}</h1>

<ul>
  {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'astrologuesser:detail' question.id %}">Vote again?</a>